export const SET_DANH_SACH_PHONG = "SET_DANH_SACH_PHONG";
export const SET_CHI_TIET_PHONG = "SET_CHI_TIET_PHONG";
export const DAT_PHONG_ACTION = "DAT_PHONG_ACTION";
export const SET_DANH_SACH_PHONG_FILTER = "SET_DANH_SACH_PHONG_FILTER";
